# SPDX-License-Identifier: AGPL-3.0-only

"""PDF to Word (pdf2docx). Decision 4: text, paragraphs and tables are carried over as editable content; the layout
may differ on multi-column or image-heavy pages. Scanned PDFs are rejected before conversion (OCR is planned for a
later phase)."""

from datetime import UTC, datetime

from docx import Document
from pdf2docx import Converter

from pdfb_convert.errors import ScannedPdf, Unreadable
from pdfb_convert.pdf import open_pdf
from pdfb_convert.scan import is_scanned, page_char_counts

# The python-docx template carries the author "python-docx", the comment "generated by python-docx" and a 2013 date;
# the input's metadata must not reach any field either. All are cleared, and the dates become the conversion time.
_EMPTY_CORE = ("author", "comments", "title", "subject", "keywords", "category", "last_modified_by", "identifier")


def _neutral_core_properties(dst: str) -> int:
    """Clears the core properties, rewrites the file and returns the number of tables."""
    try:
        document = Document(dst)
    except Exception as exc:  # noqa: BLE001 - if the produced DOCX cannot be opened, pdf2docx could not read the input
        raise Unreadable() from exc
    props = document.core_properties
    for field in _EMPTY_CORE:
        setattr(props, field, "")
    now = datetime.now(UTC).replace(tzinfo=None, microsecond=0)
    props.created = now
    props.modified = now
    props.revision = 1
    document.save(dst)
    return len(document.tables)


def convert_word(src: str, dst: str, max_pages: int) -> dict[str, int]:
    doc = open_pdf(src, max_pages)
    try:
        counts = page_char_counts(doc)
    except MemoryError:
        raise
    except Exception as exc:  # noqa: BLE001 - MuPDF errors such as a page tree cycle are raised while reading pages
        raise Unreadable() from exc
    finally:
        doc.close()
    if is_scanned(counts):
        raise ScannedPdf()

    converter = Converter(src)
    try:
        # Multi-processing is off: one process per slot and a cgroup pids.max (spec §4.5, §4.7). A failing page is not
        # skipped silently (pdf2docx skips by default): an incomplete document is not a success, the error becomes
        # CONVERT_FAILED.
        converter.convert(dst, multi_processing=False, ignore_page_error=False)
    finally:
        converter.close()

    return {"pages": len(counts), "tables": _neutral_core_properties(dst)}
